defaults:
  - dataset: appa_real
  - model: resnet18
  - training: training
  - logging: logging
  - _self_

  # Глобальные настройки
seed: 5
ckpt_path: null
run_id: null

# Настройки проекта (для информации, могут использоваться в логгерах)
project:
  name: "age-by-face"
  description: "Age estimation from face images"

# Настройки Hydra для управления запусками
hydra:
  # Создаёт папки для логов и запусков (одиночные)
  run:
    dir: ./outputs/${model.type}/${dataset.name}/${dataset.target_age}/${now:%Y-%m-%d_%H-%M-%S}
  # Создаёт папки для логов и запусков (с несколькими запусками, например, по сетке параметров)
  sweep:
    dir: ./multirun/${model.type}/${dataset.name}/${dataset.target_age}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

  # Чтоб отключить создание .hydra папки
  # output_subdir: null
